stages:
 - build
 - doc
 
before_script:
 - pwd
 - git status
 - mkdir build/
  
  
b:
 stage: build
 script:
   - cd build/
   - cmake ..
   - cmake --build .


pages:
 stage: doc
 script:
  - cd build/
  - echo "doc script"
  - cmake ..
  - make doc
  - mv doc/html/ ../public/
 artifacts:
    paths:
    - public
