stages:
  - build
  - test
  - doc

before_script:
  - pwd
  - git status
  - mkdir build/


compile_client_api:
  stage: build
  script:
    - cd build/
    - cmake ..
    - cmake --build .

compile_server:
  stage: build
  script:
    - cd build/
    - cmake -DSERVER=True -DCMAKE_INSTALL_PREFIX=/tmp/devel/ ..
    - cmake --build .

test0:
  stage: test
  script:
    - cd build/
    - ctest --output-on-failure

pages:
  stage: doc
  script:
    - cd build/
    - echo "doc script"
    - cmake ..
    - make doc
    - mv doc/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - master
