variables:
  GIT_SUBMODULE_STRATEGY: normal
  
stages:
  - build
  - test
  - doc

before_script:
  - git status



compile_client_api:
  stage: build
  script:
    - mkdir build/
    - cd build/
    - cmake ..
    - cmake --build .

compile_server:
  stage: build
  script:
    - mkdir build/
    - cd build/
    - cmake -DSERVER=True -DDO_INSTRUMENTS=True -DCMAKE_INSTALL_PREFIX=/tmp/devel/ ..
    - cmake --build .
  artifacts:
    paths:
      - build/

test0:
  stage: test
  needs:
    - job: compile_server
      artifacts: true
  script:
    - cd build/
    - ctest --output-on-failure -L client
    - ctest --output-on-failure -L mcstas
    - ctest --output-on-failure -L server
    
pages:
  stage: doc
  script:
    - cd build/
    - echo "doc script"
    - cmake ..
    - make doc
    - mv doc/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - master
